_BASE_: "Base-RCNN-FPN.yaml"
OUTPUT_DIR: "output_ICSI"
VIS_PERIOD: 0
SEED: -1  
CUDNN_BENCHMARK: False
MODEL:
  DEVICE: "cuda"
  KEYPOINT_ON: True
  ROI_HEADS: 
    NUM_CLASSES: 2
    BATCH_SIZE_PER_IMAGE: 32
    SCORE_THRESH_TEST: 0.1
  ROI_BOX_HEAD:
    SMOOTH_L1_BETA: 0.5
  ROI_KEYPOINT_HEAD:
    NAME: "KRCNNConvDeconvUpsampleHead"
    POOLER_RESOLUTION: 14
    NUM_KEYPOINTS: 4
    NORMALIZE_LOSS_BY_VISIBLE_KEYPOINTS: True
    MIN_KEYPOINTS_PER_IMAGE: 1 
    POOLER_SAMPLING_RATIO: 0
    MIN_KEYPOINTS_PER_IMAGE: 1
    POOLER_TYPE: "ROIAlignV2"
    LOSS_WEIGHT: 1.0
    NUM_KEYPOINTS: 4
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  RESNETS:
    DEPTH: 101
  RETINANET:
    NUM_CLASSES: 2
  RPN:
    POST_NMS_TOPK_TRAIN: 1500

SOLVER:
  BASE_LR: 0.0025  # pick a good LR
  STEPS: (210000, 250000)
  MAX_ITER: 92000
  IMS_PER_BATCH: 64
  IMS_PER_BATCH: 16
  CHECKPOINT_PERIOD: 5000
INPUT:
  MIN_SIZE_TRAIN: (640, 704, 736, 768, 800, 1200)
  MIN_SIZE_TEST: 1000
  MAX_SIZE_TEST: 1500

TEST:
  KEYPOINT_OKS_SIGMAS: [1., 2., 4., 4.]
DATALOADER:
  NUM_WORKERS: 12